version: "3.8"
services:
  mongodb:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - challenge-network
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - challenge-network      
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1     
      KAFKA_JMX_PORT: 9991      
    depends_on:
      - zookeeper
    networks:
      - challenge-network

  transaction-service-app:
    build:
      context: ./transaction-service-app
    container_name: transaction-service-app
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - kafka
    networks:
      - challenge-network

  antifraud-service-app:
    build:
      context: ./antifraud-service-app
    container_name: antifraud-service-app
    ports:
      - "8000:8080"
    depends_on:
      - kafka
    networks:
      - challenge-network      
volumes:
  mongo-data:
networks:
  challenge-network: